#!/bin/bash
###########################################################
##three parameters for launching wasabi on the webbrowser##
##$1:userid of wasabi				 	 ##
##$2:the target xml file                                 ##
##$3:library name for the target result                  ##
###########################################################
if [ $# -ne 3 ]; then
	printf "\033[96mNeed three parameters to launch wasabi:
##########################################################
##1:userid of wasabi                                    ##
##2:the target xml file                                 ##
##3:library name for the target result                  ##
##########################################################\033[0m\n"
else
	python canopy/wasabi.py $1 $2 $3
fi
